---
# See https://github.com/jvautier/project-cli
fullname: jvautier/docker-compose-elasticsearch
description: Docker-compose development stack with elasticsearch.
tags:
  - development
  - docker
  - docker-compose
  - elasticsearch
github: {}
