version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    command: ["bin/elasticsearch", "-Ediscovery.type=single-node"]
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ES_VERSION}
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      no_proxy: ${no_proxy},localhost,elasticsearch,kibana
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    depends_on:
      - elasticsearch